---
title: "Jacob Talbot"
author: J Talbot
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
knit: pagedown::chrome_print
editor_options: 
  chunk_output_type: console
---

```{r, echo=F, warning=F}
library(pagedown)
```

Aside
================================================================================

Kontakt {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> jtal0007@regionh.dk
- <i class="fa fa-phone"></i> +45 60653360 / 38633205
- <i class="fa fa-user-circle"></i> 33 år, gift, 2 børn (3 og 4 år)

--------------------------------------------------------------------------------

* **Medicinsk ekspert**
- *Erfaring indenfor intern medicin og kirurgi*
- *Hjertestophold*
- *Lumbalpunkturer*
- *Suturering*
- *Pleuradræn*
- *Trakeostomipleje*
- *Allergivaccination og anafylaksibehandling*

* **Kommunikator**
+ *Undervisning af stud. med.*
+ *Tutor på medicinstudiet*
+ *Initiativ og udførelse af excelkursus for medicinstuderende*

* **Samarbejder**
+ *Skadestue*
+ *Akutmodtagelse*
+ *DC-konvertering*

* **Leder**
+ *Primær investigator single-center RCT*
+ *Superviseret traumeleder*

* **Sundhedsfremmer**
+ *Medvirket til udarbejdelse af "Lægebog for Søfarende"*

* **Akademiker**
+ *Planlægning, udførelse og afslutning af klinisk lægemiddelforsøg*
+ *Erfaring med laboratorieanalyser af biomarkører og celledyrkning*
+ *Data analyse og programmering i R*

* **Professionel**

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Main
================================================================================

Jacob Lando Talbot {#title}
--------------------------------------------------------------------------------

Klinik {data-icon=hospital}
--------------------------------------------------------------------------------

### Klinisk basisuddannelse

Intern medicin / Ortopædkirurgi

Amager og Hvidovre Hospital

2018 - 2016

### Reservelæge, uklassificeret

Neurologisk afdeling

Bispebjerg Hospital

2016

### Studentermedhjælper

Lunge- og allergiklinikken

Charlottenlund

2016 - 2013

### Reservelægevikar

Ortopædkirurgisk afdeling

Nykøbing Falster Sygehus

2013 - 2012

### Ventilatør

FADL

N/A

2012 - 2010

Uddannelse / kurser {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### Kandidat i medicin

N/A

Københavns Universitet

2016 - 2009

### Kursus i suturering (del 1)

N/A

CEKU

2017

### Kursus i trakeostomi

N/A

CEKU

2017

### Kursus i lumbalpunktur

N/A

CEKU

2017

### 2 dages observatør ved lægeambulancen

N/A

AMK

2015

### Summer school, internal medicine

N/A

Københavns Universitet

2015

Forskning {data-icon = microscope}
--------------------------------------------------------------------------------

### PhD studerende

Dansk Multipel Sklerose Center

Rigshospitalet Glostrup

2021 - 2018   

Neuroimmunologisk dysregulering ved primær progressiv multipel sklerose

### Forskningsårsstuderende

Dansk Multipel Sklerose Center

Rigshospitalet, Blegdamsvej

2016 - 2015

- Immunologiske analyser af humane mesenkymale stamceller.

Publikationer {data-icon = file data-concise=TRUE}
--------------------------------------------------------------------------------

### Dimethyl fumarate treatment in primary progressive multiple sclerosis: a randomized controlled phase 2 trial.

Talbot J, Chow H et al.

N/A

2020

Under review.